### ISSUE TITLE
Error in running tutorial

### ISSUE THREAD

**Issue by nawashy** [broadinstitute/keras-rcnn#161]
Hi there,

I'm trying to run the tutorial in the Getting started but when I issue the command
(target_bounding_boxes, target_image, target_scores, _), _ = generator.next()
it gives me an error 
keras_rcnn/preprocessing/_object_detection.py in _get_batches_of_transformed_samples(self, selection)
     91 
     92             while count == 0:
---> 93                 path = self.dictionary[image_index]["filename"]
     94                 image = skimage.io.imread(path)
     95 

TypeError: only integer scalar arrays can be converted to a scalar index

can anybody help

thanks

**Comment by K-Mike** [comment]
I have the same. I think that we use different version of Keras.

**Comment by K-Mike** [comment]
Solved. upgrade  to 2.1.3

**Comment by 0x00b1** [comment]
Yeah! I apologize for this. Keras broke API compatibility with 2.1.3 (by introducing that method). We should probably specify the Keras version in our setup.py.

**Comment by nawashy** [comment]
thank
