### ISSUE TITLE
AttributeError: module 'keras.engine' has no attribute 'topology'

### ISSUE THREAD

**Issue by aseylys** [broadinstitute/keras-rcnn#206]
The `ObjectProposal` class in `.layers.objection_detection` is the one causing this error.
This seems to be because of the upgrade of Keras from 2.1.6 to 2.2.

A lot of the online chatter says to just change all instances of `topology` to `saving`, that doesn't seem to work in your code.

Is there a solution that doesn't involve downgrading Keras?

**Temporary Fix:**
Replace `keras.engine.topology.Layer` with `keras.engine.base_layer.Layer`, I don't know if this is how they're going to want it from now on, but for now it works.

**Comment by 0x00b1** [comment]
Hi, @aseylys! I appreciate the debugging. I think your recommended fix is indeed the best fix!

I'll work on a patch now.

**Comment by 0x00b1** [comment]
https://github.com/broadinstitute/keras-rcnn/pull/208

**Comment by 0x00b1** [comment]
Merged. :)
