### ISSUE TITLE
where is the starting point 

### ISSUE THREAD

**Issue by akshaylamba** [broadinstitute/keras-rcnn#36]
How do start training on the malaria data...

If Somebody can Help...

I Did Run Setup.py but could not Figure out...

I am Finding it Difficult to start as there is no README...pls help regarding training on malaria data ...

**Comment by 0x00b1** [comment]
Hi, @akshaylamba!

keras-rcnn is still a work-in-progress. I wouldn’t recommend experimenting with the package for a few weeks unless you’d like to contribute! If you’re interested in contributing, I recommend starting with the aforementioned malaria dataset and the ObjectDetection generator:

```Python
import keras_rcnn.datasets.malaria

training, test = keras_rcnn.datasets.malaria.load_data()

generator = keras_rcnn.preprocessing.ObjectDetectionGenerator()

generator = generator.flow(training)

validation_data = keras_rcnn.preprocessing.ObjectDetectionGenerator()

validation_data = generator.flow(test)
```
